OregonDigital/hyrax-migrator

.gitignore
Dockerfile
Gemfile.lock
README.md
build/install_gems.sh
config.ru
docker-compose.override.yml-example
docker-compose.yml
hyrax-migrator.gemspec

files are stripped down from OD2, possibly too stripped down
I'm building with docker-compose but running with 
docker run -it hyrax-migrator_app
because there's nothing to keep the container running (eg like launching rails -s)
there's probably a better way...

Add docker

---

.gitignore
.rubocop.yml
Gemfile.lock
app/models/hyrax/migrator/work.rb
db/migrate/20181213181357_create_hyrax_migrator_works.rb
hyrax-migrator.gemspec
lib/hyrax/migrator/engine.rb
spec/dummy/db/schema.rb
spec/factories/works.rb
spec/hyrax/migrator/work_spec.rb
spec/rails_helper.rb
spec/support/factory_bot.rb

generate work model

---

Gemfile.lock
app/actors/hyrax/migrator/actors/abstract_actor.rb
hyrax-migrator.gemspec

adds abstract actor

---

.gitignore
Dockerfile
Gemfile.lock
app/jobs/hyrax/migrator/application_job.rb
bin/rails
config.ru
docker-compose.override.yml-example
docker-compose.yml
hyrax-migrator.gemspec
lib/hyrax/migrator.rb
lib/hyrax/migrator/configuration.rb
lib/hyrax/migrator/engine.rb
spec/dummy/config/environments/test.rb
spec/dummy/config/initializers/hyrax_migrator.rb
spec/dummy/config/initializers/hyrax_migrator_middleware.rb
spec/dummy/config/initializers/sidekiq.rb
spec/dummy/config/redis.yml
spec/dummy/config/routes.rb

adds test environment, redis, and sidekiq to the engine

Sidekiq, Redis, and Test Env

---

app/actors/hyrax/migrator/actors/persist_work_actor.rb
app/models/hyrax/migrator/work.rb
app/services/hyrax/migrator/services/persist_work_service.rb
spec/hyrax/migrator/actors/persist_work_actor_spec.rb
spec/hyrax/migrator/services/persist_work_service_spec.rb
spec/hyrax/migrator/work_spec.rb

basic foundation for persist work service and actor

---

lib/hyrax/migrator/engine.rb

..and removes an invalid override

removes invalid rubocop override

---

app/actors/hyrax/migrator/actors/crosswalk_metadata_actor.rb
spec/hyrax/migrator/actors/crosswalk_metadata_actor_spec.rb

add crosswalk_metadata_actor

---

Gemfile.lock
hyrax-migrator.gemspec
lib/hyrax/migrator/configuration.rb
spec/dummy/config/initializers/hyrax_migrator.rb
spec/factories/configuration.rb
spec/hyrax/migrator/configuration_spec.rb

Adds migration_user to the configuration, adds coverage for that class, and includes pry-byebug for debugging.

migration_user configuration

---

app/actors/hyrax/migrator/actors/model_lookup_actor.rb
app/actors/hyrax/migrator/actors/persist_work_actor.rb
app/services/hyrax/migrator/services/model_lookup_service.rb
app/services/hyrax/migrator/services/persist_work_service.rb
lib/hyrax/migrator.rb
lib/hyrax/migrator/hyrax_core/actor_stack.rb
spec/factories/works.rb
spec/hyrax/migrator/hyrax_core/actor_stack_spec.rb
spec/hyrax/migrator/services/persist_work_service_spec.rb

implements an API seam for accessing Hyrax core functionality, then refactors the persistence service to make use of it.
fixes #45

refactors persistence to use hyrax core actor stack

---

app/services/hyrax/migrator/services/admin_set_membership_service.rb
spec/hyrax/migrator/services/admin_set_membership_service_spec.rb

Admin set membership service

---

app/actors/hyrax/migrator/actors/file_upload_actor.rb
app/services/hyrax/migrator/services/file_upload_service.rb
lib/hyrax/migrator.rb
lib/hyrax/migrator/hyrax_core/uploaded_file.rb
spec/hyrax/migrator/actors/file_upload_actor_spec.rb
spec/hyrax/migrator/hyrax_core/uploaded_file_spec.rb
spec/hyrax/migrator/services/file_upload_service_spec.rb

Feature file upload actor

---

app/actors/hyrax/migrator/actors/abstract_actor.rb
app/actors/hyrax/migrator/actors/bag_validator_actor.rb
app/actors/hyrax/migrator/actors/crosswalk_metadata_actor.rb
app/actors/hyrax/migrator/actors/file_upload_actor.rb
app/actors/hyrax/migrator/actors/model_lookup_actor.rb
app/actors/hyrax/migrator/actors/persist_work_actor.rb
app/actors/hyrax/migrator/actors/terminal_actor.rb
app/services/hyrax/migrator/services/persist_work_service.rb
lib/hyrax/migrator.rb
lib/hyrax/migrator/hyrax_core/actor_stack.rb
lib/hyrax/migrator/hyrax_core/user.rb
spec/hyrax/migrator/actors/abstract_actor_spec.rb
spec/hyrax/migrator/hyrax_core/actor_stack_spec.rb

moves the success, failure, and work updating methods to the abstract actor. 
fixes #58

moves common functionality into abstract actor

---

app/models/concerns/hyrax/migrator/has_working_directory.rb
spec/hyrax/migrator/work_spec.rb

extends has working directory to handle s3 download files

---

app/actors/hyrax/migrator/actors/admin_set_membership_actor.rb
spec/hyrax/migrator/actors/admin_set_membership_actor_spec.rb

admin_set_membership_actor

---

app/models/hyrax/migrator/work.rb

adds defaults for expected methods

---

app/actors/hyrax/migrator/actors/persist_work_actor.rb

fixes bug in persist work actor calling user

---

app/actors/hyrax/migrator/actors/admin_set_membership_actor.rb
app/actors/hyrax/migrator/actors/bag_validator_actor.rb
app/actors/hyrax/migrator/actors/crosswalk_metadata_actor.rb
app/actors/hyrax/migrator/actors/file_upload_actor.rb
app/actors/hyrax/migrator/actors/model_lookup_actor.rb
app/actors/hyrax/migrator/actors/persist_work_actor.rb
app/services/hyrax/migrator/services/file_upload_service.rb
spec/hyrax/migrator/services/file_upload_service_spec.rb

add traceback info when logging errors

---

app/services/hyrax/migrator/services/crosswalk_metadata_service.rb
spec/hyrax/migrator/services/crosswalk_metadata_service_spec.rb

Crosswalk overrides

---

app/services/hyrax/migrator/services/crosswalk_metadata_service.rb
spec/fixtures/crosswalk.yml
spec/hyrax/migrator/services/crosswalk_metadata_service_spec.rb

provides a nested attributes data function

---

app/actors/hyrax/migrator/actors/file_upload_actor.rb
spec/hyrax/migrator/actors/file_upload_actor_spec.rb
spec/hyrax/migrator/services/file_upload_service_spec.rb

Fix user in file upload actor

---

app/services/hyrax/migrator/services/persist_work_service.rb
spec/hyrax/migrator/services/persist_work_service_spec.rb

add error backtrace to persist work service logging

---

app/services/hyrax/migrator/services/add_relationships_service.rb
lib/hyrax/migrator/hyrax_core/actor_stack.rb
spec/hyrax/migrator/services/add_relationships_service_spec.rb

Add relationships service

---

app/services/hyrax/migrator/services/list_children_service.rb
spec/hyrax/migrator/services/list_children_service_spec.rb

List children service

---

docker-compose.yml

docker-compose wasn't standing up and properly binding the dummy app for testing

fixes docker-compose to run dummy app

---

app/actors/hyrax/migrator/actors/add_relationships_actor.rb
spec/hyrax/migrator/actors/add_relationships_actor_spec.rb

Add relationships actor

---

app/actors/hyrax/migrator/actors/list_children_actor.rb
spec/hyrax/migrator/actors/list_children_actor_spec.rb

List children actor2

---

app/jobs/hyrax/migrator/jobs/migrate_work_job.rb
app/services/hyrax/migrator/services/migrate_work_service.rb
spec/hyrax/migrator/jobs/migrate_work_job_spec.rb
spec/hyrax/migrator/middleware/default_middleware_spec.rb
spec/hyrax/migrator/services/migrate_work_service_spec.rb
spec/support/factory_bot.rb

Migrate work job

---

app/services/hyrax/migrator/services/admin_set_membership_service.rb
lib/hyrax/migrator.rb
lib/hyrax/migrator/configuration.rb
lib/hyrax/migrator/hyrax_core/admin_set.rb
spec/dummy/config/initializers/hyrax_migrator.rb
spec/fixtures/crosswalk_admin_sets.yml
spec/hyrax/migrator/configuration_spec.rb
spec/hyrax/migrator/services/admin_set_membership_service_spec.rb

add crosswalk admin sets and hyrax core adminset

---

app/services/hyrax/migrator/services/visibility_lookup_service.rb
spec/hyrax/migrator/services/visibility_lookup_service_spec.rb

Visibility service

---

app/actors/hyrax/migrator/actors/visibility_lookup_actor.rb
spec/hyrax/migrator/actors/visibility_lookup_actor_spec.rb

fixes #73 (along with visibility service)

visibility actor

---

app/services/hyrax/migrator/services/admin_set_membership_service.rb
lib/hyrax/migrator/hyrax_core/admin_set.rb
spec/fixtures/crosswalk_admin_sets.yml
spec/hyrax/migrator/services/admin_set_membership_service_spec.rb

match primary sets using adminset ids

---

app/actors/hyrax/migrator/actors/crosswalk_metadata_actor.rb
app/jobs/hyrax/migrator/jobs/migrate_work_job.rb
app/services/hyrax/migrator/services/migrate_work_service.rb
lib/hyrax/migrator/hyrax_core/actor_stack.rb
spec/hyrax/migrator/actors/crosswalk_metadata_actor_spec.rb
spec/hyrax/migrator/services/migrate_work_service_spec.rb

These are fixes to some bugs that were identified while I was testing the migrate work service and job.

fixes bugs found related to migrate work testing

---

app/actors/hyrax/migrator/actors/add_relationships_actor.rb
app/actors/hyrax/migrator/actors/children_audit_actor.rb
app/actors/hyrax/migrator/actors/list_children_actor.rb
app/services/hyrax/migrator/services/children_audit_service.rb
lib/hyrax/migrator.rb
lib/hyrax/migrator/configuration.rb
lib/hyrax/migrator/hyrax_core/asset.rb
spec/hyrax/migrator/actors/add_relationships_actor_spec.rb
spec/hyrax/migrator/actors/children_audit_actor_spec.rb
spec/hyrax/migrator/actors/list_children_actor_spec.rb
spec/hyrax/migrator/services/children_audit_service_spec.rb

Child exists

---

app/actors/hyrax/migrator/actors/admin_set_membership_actor.rb

remove set and admin_set from attributes

---

app/actors/hyrax/migrator/actors/admin_set_membership_actor.rb
app/services/hyrax/migrator/services/admin_set_membership_service.rb
app/services/hyrax/migrator/services/create_graph_service.rb
app/services/hyrax/migrator/services/crosswalk_metadata_service.rb
spec/fixtures/crosswalk_overrides.yml
spec/hyrax/migrator/actors/admin_set_membership_actor_spec.rb
spec/hyrax/migrator/services/admin_set_membership_service_spec.rb
spec/hyrax/migrator/services/create_graph_service_spec.rb
spec/hyrax/migrator/services/crosswalk_metadata_service_spec.rb

add create graph service

---

.circleci/config.yml
app/services/hyrax/migrator/services/bag_ingest_service.rb
spec/fixtures/crosswalk_overrides.yml
spec/hyrax/migrator/services/bag_ingest_service_spec.rb

fixes https://github.com/OregonDigital/hyrax-migrator/issues/110

add bag_ingest_service

---

app/services/hyrax/migrator/services/crosswalk_metadata_service.rb
lib/hyrax/migrator/configuration.rb
spec/hyrax/migrator/configuration_spec.rb
spec/hyrax/migrator/services/crosswalk_metadata_service_spec.rb

Skip field mode

---

lib/hyrax/migrator/middleware.rb

use new config everytime for default

---

app/services/hyrax/migrator/services/admin_set_membership_service.rb
lib/hyrax/migrator/configuration.rb
spec/fixtures/crosswalk_admin_sets.yml
spec/hyrax/migrator/services/admin_set_membership_service_spec.rb

fallback admin sets with institution metadata

---

app/services/hyrax/migrator/services/bag_ingest_service.rb
lib/hyrax/migrator/hyrax_core/asset.rb
spec/hyrax/migrator/services/bag_ingest_service_spec.rb

skip existing works during bag ingest

---

app/actors/hyrax/migrator/actors/add_relationships_actor.rb
app/services/hyrax/migrator/services/add_relationships_service.rb
app/services/hyrax/migrator/services/children_audit_service.rb
lib/hyrax/migrator/configuration.rb
lib/hyrax/migrator/hyrax_core/actor_stack.rb
lib/hyrax/migrator/middleware/configuration.rb
spec/hyrax/migrator/middleware/configuration_spec.rb
spec/hyrax/migrator/services/children_audit_service_spec.rb

Fix add relationships

---

app/services/hyrax/migrator/services/admin_set_membership_service.rb
spec/hyrax/migrator/services/admin_set_membership_service_spec.rb

Updating to `admin_set_id` in admin_set_membership_service and allow it to retrieve values directly from the nt desc file for both `primary_set` and `institution`. This will be useful for `institution` so that we can update its format in the crosswalk as needed in #144

retrieve institution from nt file to match admin_set_id

---

app/services/hyrax/migrator/services/crosswalk_metadata_service.rb
spec/hyrax/migrator/services/crosswalk_metadata_service_spec.rb

Add uri check

---

app/serializers/hyrax/migrator/serializers/middleware_configuration_serializer.rb
app/services/hyrax/migrator/services/bag_ingest_service.rb
app/services/hyrax/migrator/services/migrate_work_service.rb
lib/hyrax/migrator/middleware.rb
spec/hyrax/migrator/middleware_spec.rb
spec/hyrax/migrator/serializers/middleware_configuration_serializer_spec.rb
spec/hyrax/migrator/services/migrate_work_service_spec.rb

Add custom middleware

---

app/services/hyrax/migrator/services/bag_ingest_service.rb
spec/hyrax/migrator/services/bag_ingest_service_spec.rb

update bag_ingest_service to allow restart service on failed works

---

app/actors/hyrax/migrator/actors/crosswalk_metadata_actor.rb
app/services/hyrax/migrator/services/crosswalk_metadata_service.rb
spec/hyrax/migrator/actors/crosswalk_metadata_actor_spec.rb
spec/hyrax/migrator/services/crosswalk_metadata_service_spec.rb

stash crosswalk errors

---

app/services/hyrax/migrator/services/list_children_service.rb
spec/fixtures/df72jn67c/data/df72jn67c_descMetadata.nt
spec/hyrax/migrator/services/list_children_service_spec.rb

partially fulfills #157 
will also need to update the overrides file on OD2

use graph in list children

---

app/services/hyrax/migrator/services/file_upload_service.rb
spec/hyrax/migrator/services/file_upload_service_spec.rb

implement ensure_integrity_of content in file_upload_service

---

app/services/hyrax/migrator/services/list_children_service.rb
spec/hyrax/migrator/services/list_children_service_spec.rb

use rdf reader to preserve order

---

app/services/hyrax/migrator/services/crosswalk_metadata_service.rb
spec/fixtures/crosswalk.yml
spec/hyrax/migrator/services/crosswalk_metadata_service_spec.rb

implement datetime_data function for crosswalk metadata service

---

app/services/hyrax/migrator/services/crosswalk_metadata_service.rb
spec/hyrax/migrator/services/crosswalk_metadata_service_spec.rb

cast to string before returning object for datetime_data

---

.rubocop.yml
app/services/hyrax/migrator/services/crosswalk_metadata_service.rb
lib/hyrax/migrator.rb
lib/hyrax/migrator/crosswalk_metadata.rb
lib/hyrax/migrator/crosswalk_metadata_preflight.rb
lib/tasks/preflight_tools/metadata_preflight.rake
spec/fixtures/pidlist
spec/hyrax/migrator/crosswalk_metadata_preflight_spec.rb
spec/hyrax/migrator/crosswalk_metadata_spec.rb
spec/hyrax/migrator/services/crosswalk_metadata_service_spec.rb
spec/support/rake.rb
spec/tasks/preflight_tools/rake_spec.rb

move crosswalk metadata service code to lib

---

app/actors/hyrax/migrator/actors/required_fields_actor.rb
app/services/hyrax/migrator/services/required_fields_service.rb
lib/hyrax/migrator/configuration.rb
lib/hyrax/migrator/crosswalk_metadata_preflight.rb
lib/hyrax/migrator/middleware/configuration.rb
lib/hyrax/migrator/required_fields.rb
lib/tasks/preflight_tools/metadata_preflight.rake
spec/fixtures/crosswalk_overrides.yml
spec/fixtures/required_fields.yml
spec/hyrax/migrator/actors/required_fields_actor_spec.rb
spec/hyrax/migrator/middleware/configuration_spec.rb
spec/hyrax/migrator/required_fields_spec.rb
spec/hyrax/migrator/services/required_fields_service_spec.rb
spec/tasks/preflight_tools/rake_spec.rb

Verify required

---

app/services/hyrax/migrator/services/verification_service.rb
app/services/hyrax/migrator/services/verify_checksums_service.rb
app/services/hyrax/migrator/services/verify_metadata_service.rb
spec/hyrax/migrator/services/verification_service_spec.rb
spec/hyrax/migrator/services/verify_checksums_service_spec.rb
spec/hyrax/migrator/services/verify_metadata_service_spec.rb

Breakup service

---

app/services/hyrax/migrator/services/visibility_lookup_service.rb
lib/hyrax/migrator.rb
lib/hyrax/migrator/preflight_checks.rb
lib/hyrax/migrator/visibility_lookup.rb
lib/hyrax/migrator/visibility_lookup_preflight.rb
spec/hyrax/migrator/preflight_checks_spec.rb
spec/hyrax/migrator/services/visibility_lookup_service_spec.rb
spec/hyrax/migrator/visibility_lookup_preflight_spec.rb
spec/hyrax/migrator/visibility_lookup_spec.rb

Access check

---

lib/hyrax/migrator/visibility_lookup.rb
spec/hyrax/migrator/services/visibility_lookup_service_spec.rb
spec/hyrax/migrator/visibility_lookup_spec.rb

fix mapping

---

app/actors/hyrax/migrator/actors/abstract_actor.rb
app/actors/hyrax/migrator/actors/persist_work_actor.rb
app/services/hyrax/migrator/services/persist_work_service.rb
spec/hyrax/migrator/actors/persist_work_actor_spec.rb
spec/hyrax/migrator/services/persist_work_service_spec.rb

Save persist messages

---

app/services/hyrax/migrator/services/batch_reporter_service.rb
spec/dummy/config/initializers/hyrax_migrator.rb
spec/hyrax/migrator/services/batch_reporter_service_spec.rb

Batch reporter

---

app/actors/hyrax/migrator/actors/persist_work_actor.rb
spec/hyrax/migrator/actors/persist_work_actor_spec.rb

persist actor check

---

app/services/hyrax/migrator/services/admin_set_membership_service.rb
spec/hyrax/migrator/services/admin_set_membership_service_spec.rb

fail if admin set lookup fails

---

app/services/hyrax/migrator/services/verify_checksums_service.rb
spec/hyrax/migrator/services/verify_checksums_service_spec.rb

handle no checksums

---

app/services/hyrax/migrator/services/verify_children_service.rb
spec/hyrax/migrator/services/verify_children_service_spec.rb

check for nil child

---

app/jobs/hyrax/migrator/jobs/migrate_work_job.rb
spec/hyrax/migrator/jobs/migrate_work_job_spec.rb

job logging

---

lib/hyrax/migrator/cpd_check.rb
lib/hyrax/migrator/crosswalk_metadata_preflight.rb
lib/hyrax/migrator/preflight_check_services.rb
lib/hyrax/migrator/preflight_checks.rb
lib/hyrax/migrator/visibility_lookup_preflight.rb
spec/fixtures/pidlist
spec/hyrax/migrator/cpd_check_spec.rb
spec/hyrax/migrator/crosswalk_metadata_preflight_spec.rb
spec/hyrax/migrator/preflight_check_services_spec.rb
spec/hyrax/migrator/preflight_checks_spec.rb
spec/hyrax/migrator/visibility_lookup_preflight_spec.rb

add checks to preflight

---

app/services/hyrax/migrator/services/verification_service.rb
app/services/hyrax/migrator/services/verify_checksums_service.rb
app/services/hyrax/migrator/services/verify_children_service.rb
app/services/hyrax/migrator/services/verify_derivatives_service.rb
app/services/hyrax/migrator/services/verify_metadata_service.rb
app/services/hyrax/migrator/services/verify_visibility_service.rb
spec/fixtures/data/df70jh899_profile.yml
spec/hyrax/migrator/services/verify_checksums_service_spec.rb
spec/hyrax/migrator/services/verify_children_service_spec.rb
spec/hyrax/migrator/services/verify_derivatives_service_spec.rb
spec/hyrax/migrator/services/verify_metadata_service_spec.rb
spec/hyrax/migrator/services/verify_visibility_service_spec.rb

fixes #247
this is the last addition, updates all the other verifiers to use the same format as the new visibility verifier.

update verifiers and their specs

---

Gemfile.lock
app/services/hyrax/migrator/services/bag_file_location_service.rb

bag location handle unzipped dirs

---

app/models/concerns/hyrax/migrator/has_working_directory.rb
lib/hyrax/migrator/middleware/configuration.rb
spec/hyrax/migrator/middleware/configuration_spec.rb
spec/hyrax/migrator/middleware_spec.rb

Less checksumming

---

app/services/hyrax/migrator/services/file_upload_service.rb
spec/hyrax/migrator/services/file_upload_service_spec.rb

do not copy file for upload

---

.rubocop.yml
Gemfile.lock
hyrax-migrator.gemspec
lib/hyrax/migrator/edtf_check.rb
lib/hyrax/migrator/preflight_check_services.rb
lib/hyrax/migrator/preflight_checks.rb
spec/hyrax/migrator/edtf_check_spec.rb
spec/hyrax/migrator/preflight_check_services_spec.rb
spec/hyrax/migrator/preflight_checks_spec.rb

Check edtf

---

.circleci/config.yml

redo circleci config to add workflows, copying the structure that was used in OD2

redo for workflows

---

app/services/hyrax/migrator/services/crosswalk_metadata_service.rb
spec/hyrax/migrator/services/crosswalk_metadata_service_spec.rb

remove props not set in crosswalk

---

app/services/hyrax/migrator/services/verify_labels_exist_service.rb
lib/hyrax/migrator/hyrax_core/asset.rb
spec/hyrax/migrator/services/verify_labels_exist_service_spec.rb

verify labels

---

app/services/hyrax/migrator/services/verify_derivatives_service.rb
spec/hyrax/migrator/services/verify_derivatives_service_spec.rb

add warnings

---

.rubocop.yml
app/services/hyrax/migrator/services/verify_checksums_service.rb
app/services/hyrax/migrator/services/verify_derivatives_service.rb
spec/hyrax/migrator/services/verify_checksums_service_spec.rb
spec/hyrax/migrator/services/verify_derivatives_service_spec.rb

report missing files

---

app/controllers/hyrax/migrator/profiles_controller.rb
app/views/hyrax/migrator/profiles/show.html.erb
spec/hyrax/migrator/controllers/profiles_controller_spec.rb
spec/hyrax/migrator/services/file_upload_service_spec.rb

follow up to #310, hopefully addresses problem with random layout behavior, and adds sorting

Profile fix

---

lib/hyrax/migrator/edtf_check.rb
lib/hyrax/migrator/preflight_checks.rb
spec/hyrax/migrator/edtf_check_spec.rb
spec/hyrax/migrator/preflight_checks_spec.rb

Preflight usability

---

app/services/hyrax/migrator/services/admin_set_membership_service.rb
spec/hyrax/migrator/services/admin_set_membership_service_spec.rb

allow multiple institutions

---

app/services/hyrax/migrator/services/verify_labels_exist_service.rb
spec/hyrax/migrator/services/verify_labels_exist_service_spec.rb

remove graphworker

---

app/services/hyrax/migrator/services/crosswalk_metadata_service.rb
spec/fixtures/crosswalk_admin_sets.yml
spec/hyrax/migrator/services/crosswalk_metadata_service_spec.rb

dont use bools

---

.rubocop.yml
app/services/hyrax/migrator/services/crosswalk_metadata_service.rb

this failed QA. reverted suggested .zero? with ==0

zero not a replacement for ==

---

app/services/hyrax/migrator/services/verify_metadata_service.rb
spec/fixtures/data/df70jh899_profile.yml
spec/hyrax/migrator/services/verify_metadata_service_spec.rb

wire up colls verify
